def number(int1=1,int2=3):
     if ():
         return 4
     elif (int1!=1):
         return int1+int2
     elif (int1!=1,int2!=3):
         return int1+int2
     elif (int2!=3):
         return int1+int2